// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmrvsqgrxpwxdmwzaiui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcnZzcWdyeHB3eGRtd3phaXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTY2OTAsImV4cCI6MjA2NjY5MjY5MH0.k73yHuXOFB6Ov2IKicbn2I94qQbwmY2qBwZlpYK-WCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);